export default {
    home: {
        position: {
            lat: 45.497253,
            lng: -73.656472,
        },
        icon: './dlbi.png',
    },
    restaurants: [
        {
            id: 1,
            position: {
                lat: 45.498576,
                lng: -73.653687,
            },
            title: 'Pushap',
            address: '5195 Pare St, Montreal, QC H4P 2B1',
            website: '',
            phone_number: '(514) 737-4527',
            has_mg_discount: false,
        },
        {
            id: 2,
            position: {
                lat: 45.494984,
                lng: -73.651778,
            },
            title: 'Kanda Sushi Bar',
            address: '7373 Boulevard Décarie',
            website: '',
            phone_number: '(514) 735-7888',
            has_mg_discount: true,
        },
        {
            id: 3,
            position: {
                lat: 45.494755,
                lng: -73.655588,
            },
            title: 'Baton Rouge',
            address: '7373 Boulevard Décarie',
            website: null,
            phone_number: '(514) 735-7888',
            has_mg_discount: false,
        },
        {
            id: 4,
            position: {
                lat: 45.496908,
                lng: -73.654956,
            },
            title: 'Otago',
            address: '7373 Boulevard Décarie',
            website: null,
            phone_number: '(514) 735-7888',
            has_mg_discount: true,
        },
        {
            id: 5,
            position: {
                lat: 45.498173,
                lng: -73.657834,
            },
            title: 'Madisons',
            address: '7373 Boulevard Décarie',
            website: 'http://madisonsresto.com',
            phone_number: '(514) 543-3131',
            has_mg_discount: false,
        },
        {
            id: 6,
            position: {
                lat: 45.497253,
                lng: -73.656472,
            },
            title: 'MG Health Trattoria',
            address: '7777 Boulevard Décarie',
            website: '',
            has_mg_discount: false,
        },
        {
            id: 7,
            position: {
                lat: 45.49711,
                lng: -73.655045,
            },
            title: 'Eggspectation',
            address: '7657 Decarie Blvd, Montreal, QC H4P 2H2',
            website: 'eggspectation.com',
            phone_number: '(514) 735-7888',
            has_mg_discount: false,
        },
        {
            id: 8,
            position: {
                lat: 45.495079,
                lng: -73.655206,
            },
            title: 'Marathon Souvlaki',
            address: '7373 Boulevard Décarie',
            website: null,
            phone_number: '(514) 735-7888',
            has_mg_discount: false,
        },
        {
            id: 9,
            position: {
                lat: 45.494106,
                lng: -73.655947,
            },
            title: 'Allô! Mon Coco',
            address: '5405 Rue des Jockeys, Montréal, QC H4P 2T7',
            website: 'https://allomoncoco.com',
            phone_number: '(514) 735-7888',
            has_mg_discount: true,
        },
        {
            id: 10,
            position: {
                lat: 45.495086,
                lng: -73.651855,
            },
            title: 'Amir',
            address: '7373 Boulevard Décarie',
            website: '',
            phone_number: '(514) 735-7888',
            has_mg_discount: true,
        },
        {
            id: 11,
            position: {
                lat: 45.495964,
                lng: -73.650859,
            },
            title: 'Boustan',
            address: '5150 Rue Jean-Talon Ouest, Montreal, QC H4P 2A7',
            website: '',
            phone_number: '(514) 735-7888',
            has_mg_discount: true,
        },
        {
            id: 12,
            position: {
                lat: 45.494655,
                lng: -73.65191,
            },
            title: 'Dunn’s',
            address: '7385 Decarie Blvd',
            website: '',
            phone_number: '(514) 731-2424',
            has_mg_discount: true,
        },
        {
            id: 13,
            position: {
                lat: 45.497774,
                lng: -73.659247,
            },
            title: 'La Prep',
            address: '8000 Decarie Blvd',
            website: 'https://laprepqctraiteur.ecwid.com',
            phone_number: '(514) 735-8233',
            has_mg_discount: true,
        },
    ],
};
