export const CURRENT_INDEX = 'CURRENT_INDEX';
export const LIST_TYPE = 'LIST_TYPE';
export const TOGGLE_FAV = 'TOGGLE_FAV';
export const TOGGLE_SURVEY = 'TOGGLE_SURVEY';
export const CANCEL_SURVEY = 'CANCEL_SURVEY';


export const CREATE_SURVEY = 'CREATE_SURVEY';
export const GET_SURVEY_SUCCESS = 'GET_SURVEY_SUCCESS';
export const VOTE_PROPOSAL = 'VOTE_PROPOSAL';
export const SURVEY_RESULTS = 'SURVEY_RESULTS';

export const REQUEST_PENDING = 'REQUEST_PENDING';

export const EXISTING_SURVEY_DELETE = 'EXISTING_SURVEY_DELETE';
export const EXISTING_SURVEY_DISPLAY = 'EXISTING_SURVEY_DISPLAY';