export const CURRENT_INDEX = 'CURRENT_INDEX';
export const LIST_TYPE = 'LIST_TYPE';
export const TOGGLE_FAV = 'TOGGLE_FAV';
export const TOGGLE_SURVEY = 'TOGGLE_SURVEY';
export const MAP_LOADED = 'MAP_LOADED';

export const ITINERARY_LOADED = 'ITINERARY_LOADED';
export const ITINERARY_CLEARED = 'ITINERARY_CLEARED';

export const RESTAURANTS_LOADED = 'RESTAURANTS_LOADED';