const texts = {
  loading: 'Chargement',
  'add_fav': 'Ajouter à ma liste',
  'del_fav': 'Retirer de ma liste',
  'close': 'Fermer',
  'display_itinerary': 'Afficher itinéraire',
  'add_survey': 'Ajouter au sondage',
  'del_survey': 'Retirer du sondage',
  'info_cal': 'Base calculée pour un individu de 80 kg à une allure de 3 km/h',
  'empty_list': 'Votre liste est vide',
  'current_survey': 'Sondage en cours',
  'cancel_survey': 'Annuler sondage',
  'generate_survey': 'Créer sondage',
  'calories_burnt': 'Calories brûlées : __placeholder__ kcal',
  'survey_links': 'Liens : ',
  'survey_': 'Sondage : ',
  'survey_results': 'Résultats : ',
  'survey_error_404': 'Bah rien. Ce sondage n\'existe plus.',
  'survey_exists': 'Un sondage existe',
  'survey_delete_existing': 'Supprimer le sondage existant',
  'survey_display_existing': 'Afficher le sondage existant',
  'add_new_restaurant_legend': 'Ajouter restaurant',
  'add_new_restaurant_submit': 'Ajouter',
  'reinit_new_restaurant_submit': 'Réinitialiser',
};

export default texts;